/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.26a.                          *
*        Compiled Aug 20 2014, 15:23:27                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: beep                                                  *
* Dimensions:  10 * 16                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP g_beep;

static GUI_CONST_STORAGE unsigned long g_res_beep[] = {
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x73BEB1A8, 0x08BEB1A8, 0x74BEB1A8,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xBCBEB1A8, 0x11BEB1A8, 0x03BEB1A8, 0x94BEB1A8, 0x00BEB1A8,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x97BEB1A8, 0x04BEB1A8, 0x0ABEB1A8, 0xB0BEB1A8, 0xFFFFFFFF, 0x00BEB1A8,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8, 0x16BEB1A8, 0xC9BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8,
  0x37BEB1A8, 0x00BEB1A8, 0x00BEB1A8, 0x00BEB1A8, 0x05BEB1A8, 0xDCBEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8,
  0x00BEB1A8, 0xC7BEB1A8, 0xFFFFFFFF, 0xC5BEB1A8, 0x00BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8,
  0x00BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8,
  0x00BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8,
  0x00BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8,
  0x00BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8,
  0x00BEB1A8, 0xC7BEB1A8, 0xFFFFFFFF, 0xC5BEB1A8, 0x00BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8,
  0x39BEB1A8, 0x00BEB1A8, 0x00BEB1A8, 0x00BEB1A8, 0x06BEB1A8, 0xDCBEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8, 0x16BEB1A8, 0xC9BEB1A8, 0xFFFFFFFF, 0xFFFFFFFF, 0x00BEB1A8,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x95BEB1A8, 0x04BEB1A8, 0x0BBEB1A8, 0xB0BEB1A8, 0xFFFFFFFF, 0x00BEB1A8,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xBBBEB1A8, 0x11BEB1A8, 0x03BEB1A8, 0x94BEB1A8, 0x00BEB1A8,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x73BEB1A8, 0x08BEB1A8, 0x74BEB1A8
};

GUI_CONST_STORAGE GUI_BITMAP g_beep = {
  10, // xSize
  16, // ySize
  40, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)g_res_beep,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
