/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.26a.                          *
*        Compiled Aug 20 2014, 15:23:27                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: line_l                                                *
* Dimensions:  120 * 1                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP g_line_l;

static GUI_CONST_STORAGE unsigned long g_res_line_l[] = {
  0xA4FFFFFF, 0x94FFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 
        0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x99FFFFFF, 0x99FFFFFF, 0x9EFFFFFF, 0x9FFFFFFF, 0x9EFFFFFF, 
        0x9EFFFFFF, 0x9DFFFFFF, 0x9FFFFFFF, 0xA4FFFFFF, 0xA3FFFFFF, 0xA3FFFFFF, 0xA3FFFFFF, 0xA3FFFFFF, 0xA7FFFFFF, 0xA8FFFFFF, 0xA7FFFFFF, 0xABFFFFFF, 0xAFFFFFFF, 0xAEFFFFFF, 0xAEFFFFFF, 0xAEFFFFFF, 0xADFFFFFF, 0xB0FFFFFF, 0xB7FFFFFF, 0xB7FFFFFF, 
        0xB6FFFFFF, 0xB5FFFFFF, 0xB5FFFFFF, 0xBBFFFFFF, 0xBBFFFFFF, 0xBBFFFFFF, 0xBFFFFFFF, 0xBFFFFFFF, 0xBEFFFFFF, 0xC3FFFFFF, 0xC7FFFFFF, 0xC6FFFFFF, 0xC6FFFFFF, 0xC5FFFFFF, 0xC9FFFFFF, 0xCDFFFFFF, 0xCBFFFFFF, 0xD0FFFFFF, 0xD3FFFFFF, 0xD2FFFFFF, 
        0xD2FFFFFF, 0xD1FFFFFF, 0xD4FFFFFF, 0xD9FFFFFF, 0xD8FFFFFF, 0xD7FFFFFF, 0xDDFFFFFF, 0xDEFFFFFF, 0xDCFFFFFF, 0xDFFFFFFF, 0xE3FFFFFF, 0xE1FFFFFF, 0xE4FFFFFF, 0xE7FFFFFF, 0xE6FFFFFF, 0xE6FFFFFF, 0xEAFFFFFF, 0xEAFFFFFF, 0xE9FFFFFF, 0xEEFFFFFF, 
        0xF2FFFFFF, 0xF1FFFFFF, 0xF1FFFFFF, 0xF1FFFFFF, 0xF0FFFFFF, 0xF0FFFFFF, 0xF5FFFFFF, 0xF8FFFFFF, 0xF7FFFFFF, 0xF6FFFFFF, 0xFBFFFFFF, 0xFEFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF
};

GUI_CONST_STORAGE GUI_BITMAP g_line_l = {
  120, // xSize
  1, // ySize
  480, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)g_res_line_l,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
