/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.26a.                          *
*        Compiled Aug 20 2014, 15:23:27                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: line_r                                                *
* Dimensions:  125 * 1                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP g_line_r;

static GUI_CONST_STORAGE unsigned long g_res_line_r[] = {
  0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xFDFFFFFF, 0xF7FFFFFF, 0xF7FFFFFF, 0xF7FFFFFF, 0xF7FFFFFF, 0xF2FFFFFF, 0xF0FFFFFF, 0xF1FFFFFF, 0xF1FFFFFF, 0xF1FFFFFF, 0xF1FFFFFF, 0xF2FFFFFF, 0xEDFFFFFF, 
        0xE9FFFFFF, 0xEAFFFFFF, 0xEAFFFFFF, 0xE6FFFFFF, 0xE6FFFFFF, 0xE7FFFFFF, 0xE5FFFFFF, 0xE1FFFFFF, 0xE3FFFFFF, 0xE0FFFFFF, 0xDCFFFFFF, 0xDDFFFFFF, 0xDEFFFFFF, 0xD9FFFFFF, 0xD7FFFFFF, 0xD9FFFFFF, 0xD7FFFFFF, 0xD2FFFFFF, 0xD2FFFFFF, 0xD2FFFFFF, 
        0xD2FFFFFF, 0xD3FFFFFF, 0xCEFFFFFF, 0xCBFFFFFF, 0xCDFFFFFF, 0xC8FFFFFF, 0xC5FFFFFF, 0xC6FFFFFF, 0xC6FFFFFF, 0xC7FFFFFF, 0xC4FFFFFF, 0xBEFFFFFF, 0xBFFFFFFF, 0xBFFFFFFF, 0xBCFFFFFF, 0xBAFFFFFF, 0xBCFFFFFF, 0xB7FFFFFF, 0xB5FFFFFF, 0xB6FFFFFF, 
        0xB6FFFFFF, 0xB7FFFFFF, 0xB4FFFFFF, 0xADFFFFFF, 0xAEFFFFFF, 0xAEFFFFFF, 0xAEFFFFFF, 0xAEFFFFFF, 0xAFFFFFFF, 0xAAFFFFFF, 0xA7FFFFFF, 0xA8FFFFFF, 0xA7FFFFFF, 0xA3FFFFFF, 0xA3FFFFFF, 0xA3FFFFFF, 0xA3FFFFFF, 0xA4FFFFFF, 0xA0FFFFFF, 0x9DFFFFFF, 
        0x9EFFFFFF, 0x9EFFFFFF, 0x9EFFFFFF, 0x9FFFFFFF, 0x9BFFFFFF, 0x99FFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 
        0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 0x9AFFFFFF, 
        0x9AFFFFFF, 0x9AFFFFFF, 0x94FFFFFF, 0xA1FFFFFF
};

GUI_CONST_STORAGE GUI_BITMAP g_line_r = {
  125, // xSize
  1, // ySize
  500, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)g_res_line_r,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
