/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.26a.                          *
*        Compiled Aug 20 2014, 15:23:27                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: slider_thumb_l                                        *
* Dimensions:  5 * 10                                                *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP g_slider_thumb_l;

static GUI_CONST_STORAGE unsigned long g_res_slider_thumb_l[] = {
  0xFFFFFFFF, 0xFFFFFFFF, 0xB2516EFC, 0x41516EFC, 0x0C516EFC,
  0xFFFFFFFF, 0x7B516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC,
  0xB3516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC,
  0x41516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC,
  0x0D516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC,
  0x0D516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC,
  0x41516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC,
  0xB2516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC,
  0xFFFFFFFF, 0x7B516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC,
  0xFFFFFFFF, 0xFFFFFFFF, 0xB1516EFC, 0x41516EFC, 0x0B516EFC
};

GUI_CONST_STORAGE GUI_BITMAP g_slider_thumb_l = {
  5, // xSize
  10, // ySize
  20, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)g_res_slider_thumb_l,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
