/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.26a.                          *
*        Compiled Aug 20 2014, 15:23:27                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: slider_thumb_r                                        *
* Dimensions:  5 * 10                                                *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP g_slider_thumb_r;

static GUI_CONST_STORAGE unsigned long g_res_slider_thumb_r[] = {
  0x0B516EFC, 0x40516EFC, 0xAF516EFC, 0xFFFFFFFF, 0xFFFFFFFF,
  0x00516EFC, 0x00516EFC, 0x00516EFC, 0x75516EFC, 0xFFFFFFFF,
  0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0xAF516EFC,
  0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0x3D516EFC,
  0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0x08516EFC,
  0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0x08516EFC,
  0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0x3D516EFC,
  0x00516EFC, 0x00516EFC, 0x00516EFC, 0x00516EFC, 0xAF516EFC,
  0x00516EFC, 0x00516EFC, 0x00516EFC, 0x73516EFC, 0xFFFFFFFF,
  0x0B516EFC, 0x40516EFC, 0xAF516EFC, 0xFFFFFFFF, 0xFFFFFFFF
};

GUI_CONST_STORAGE GUI_BITMAP g_slider_thumb_r = {
  5, // xSize
  10, // ySize
  20, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)g_res_slider_thumb_r,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
