/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.26a.                          *
*        Compiled Aug 20 2014, 15:23:27                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: up                                                    *
* Dimensions:  11 * 8                                                *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP g_up;

static GUI_CONST_STORAGE unsigned long g_res_up[] = {
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xAEFFFFFF, 0x50FFFFFF, 0xFBFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xCDFFFFFF, 0x44FFFFFF, 0xE7FFFFFF,
  0xFFFFFFFF, 0xFDFFFFFF, 0x87FFFFFF, 0x05FFFFFF, 0x00FFFFFF, 0xF0FFFFFF, 0xFFFFFFFF, 0xA8FFFFFF, 0x0FFFFFFF, 0x00FFFFFF, 0xC3FFFFFF,
  0xE7FFFFFF, 0x45FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0xE6FFFFFF, 0x63FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0xC3FFFFFF,
  0x2BFFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x49FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0xC3FFFFFF,
  0x22FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x40FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0xC3FFFFFF,
  0xD6FFFFFF, 0x2EFFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0xDAFFFFFF, 0x47FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0xC3FFFFFF,
  0xFFFFFFFF, 0xF7FFFFFF, 0x6AFFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0xF0FFFFFF, 0xFEFFFFFF, 0x8BFFFFFF, 0x05FFFFFF, 0x00FFFFFF, 0xC3FFFFFF,
  0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x94FFFFFF, 0x33FFFFFF, 0xF9FFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xB9FFFFFF, 0x26FFFFFF, 0xE0FFFFFF
};

GUI_CONST_STORAGE GUI_BITMAP g_up = {
  11, // xSize
  8, // ySize
  44, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)g_res_up,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
