/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.26a.                          *
*        Compiled Aug 20 2014, 15:23:27                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: volume_thumb_r                                        *
* Dimensions:  3 * 6                                                 *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP g_volume_thumb_r;

static GUI_CONST_STORAGE unsigned long g_res_volume_thumb_r[] = {
  0x0368D4A0, 0x4368D4A0, 0xEA68D4A0,
  0x0068D4A0, 0x0068D4A0, 0x5A68D4A0,
  0x0068D4A0, 0x0068D4A0, 0x0E68D4A0,
  0x0068D4A0, 0x0068D4A0, 0x0E68D4A0,
  0x0068D4A0, 0x0068D4A0, 0x5A68D4A0,
  0x0368D4A0, 0x4268D4A0, 0xEA68D4A0
};

GUI_CONST_STORAGE GUI_BITMAP g_volume_thumb_r = {
  3, // xSize
  6, // ySize
  12, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)g_res_volume_thumb_r,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
