/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.26a.                          *
*        Compiled Aug 20 2014, 15:23:27                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: list_pause                                            *
* Dimensions:  5 * 5                                                 *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP g_list_pause;

static GUI_CONST_STORAGE unsigned long g_res_list_pause[] = {
  0x00FFFFFF, 0x1EFFFFFF, 0xFFFFFFFF, 0x1EFFFFFF, 0x00FFFFFF,
  0x00FFFFFF, 0x1EFFFFFF, 0xFFFFFFFF, 0x1EFFFFFF, 0x00FFFFFF,
  0x00FFFFFF, 0x1EFFFFFF, 0xFFFFFFFF, 0x1EFFFFFF, 0x00FFFFFF,
  0x00FFFFFF, 0x1EFFFFFF, 0xFFFFFFFF, 0x1EFFFFFF, 0x00FFFFFF,
  0x00FFFFFF, 0x1EFFFFFF, 0xFFFFFFFF, 0x1EFFFFFF, 0x00FFFFFF
};

GUI_CONST_STORAGE GUI_BITMAP g_list_pause = {
  5, // xSize
  5, // ySize
  20, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)g_res_list_pause,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
