/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.26a.                          *
*        Compiled Aug 20 2014, 15:23:27                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: list_play_black                                       *
* Dimensions:  5 * 8                                                 *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP g_list_play_black;

static GUI_CONST_STORAGE unsigned long g_res_list_play_black[] = {
  0xA0CBC1B6, 0xEBCBC1B6, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF,
  0x00CBC1B6, 0x3BCBC1B6, 0xE6CBC1B6, 0xFFFFFFFF, 0xFFFFFFFF,
  0x00CBC1B6, 0x00CBC1B6, 0x1ACBC1B6, 0xC6CBC1B6, 0xFFFFFFFF,
  0x00CBC1B6, 0x00CBC1B6, 0x00CBC1B6, 0x07CBC1B6, 0xE8CBC1B6,
  0x00CBC1B6, 0x00CBC1B6, 0x00CBC1B6, 0x07CBC1B6, 0xE8CBC1B6,
  0x00CBC1B6, 0x00CBC1B6, 0x1BCBC1B6, 0xC6CBC1B6, 0xFFFFFFFF,
  0x00CBC1B6, 0x3CCBC1B6, 0xE7CBC1B6, 0xFFFFFFFF, 0xFFFFFFFF,
  0xA0CBC1B6, 0xEBCBC1B6, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF
};

GUI_CONST_STORAGE GUI_BITMAP g_list_play_black = {
  5, // xSize
  8, // ySize
  20, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)g_res_list_play_black,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
