/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.26a.                          *
*        Compiled Aug 20 2014, 15:23:27                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: list_play_white                                       *
* Dimensions:  5 * 7                                                 *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP g_list_play_white;

static GUI_CONST_STORAGE unsigned long g_res_list_play_white[] = {
  0x8CFFFFFF, 0xE3FFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF,
  0x00FFFFFF, 0x1FFFFFFF, 0xBEFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF,
  0x00FFFFFF, 0x00FFFFFF, 0x02FFFFFF, 0x73FFFFFF, 0xFAFFFFFF,
  0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0x00FFFFFF, 0xE1FFFFFF,
  0x00FFFFFF, 0x00FFFFFF, 0x02FFFFFF, 0x75FFFFFF, 0xFAFFFFFF,
  0x00FFFFFF, 0x1FFFFFFF, 0xBFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF,
  0x8CFFFFFF, 0xE3FFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF
};

GUI_CONST_STORAGE GUI_BITMAP g_list_play_white = {
  5, // xSize
  7, // ySize
  20, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)g_res_list_play_white,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
